lints.workspace = true

[package]
name = "gix-quote"
version = "0.6.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with various quotations used by git"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-utils = { version = "^0.3.0", path = "../gix-utils" }

bstr = { version = "1.12.0", default-features = false, features = ["std"] }
thiserror = "2.0.0"
