[package]
name = "gitoxide"
description = "A command-line application for interacting with git repositories"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
version = "0.11.0"
default-run = "gix"
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]
resolver = "2"


[[bin]]
name = "ein"
path = "src/porcelain-cli.rs"
test = false
doctest = false


[[bin]]
name = "gix"
path = "src/plumbing-cli.rs"
test = false
doctest = false

[features]
default = ["max"]

max = ["fast", "pretty-cli", "http-client-curl", "gitoxide-core-tools", "gitoxide-core-blocking-client",
       "prodash-render-line", "prodash-render-tui",
       "prodash/render-line-autoconfigure" ]

lean = ["fast", "pretty-cli", "http-client-curl", "gitoxide-core-tools", "gitoxide-core-blocking-client",
        "prodash-render-line" ]
lean-async = ["fast", "pretty-cli", "gitoxide-core-tools", "gitoxide-core-async-client",
              "prodash-render-line"]

small = ["pretty-cli", "git-features/rustsha1", "git-features/zlib-rust-backend", "prodash/progress-log", "atty"]

gitoxide-core-tools = ["gitoxide-core/organize", "gitoxide-core/estimate-hours"]
gitoxide-core-blocking-client = ["gitoxide-core/blocking-client"]
gitoxide-core-async-client = ["gitoxide-core/async-client", "futures-lite"]
http-client-curl = ["git-transport-for-configuration-only/http-client-curl"]
fast = ["git-features/parallel", "git-features/fast-sha1", "git-features/zlib-ng-compat"]

pretty-cli = [
    "gitoxide-core/serde1",
    "prodash/progress-tree",
    "prodash/progress-tree-log",
    "prodash/local-time",
    "gitoxide-core/local-time-support",
    "env_logger" ]

prodash-render-line-crossterm = ["prodash-render-line", "prodash/render-line-crossterm", "atty", "crosstermion"]

# internal
prodash-render-tui = ["prodash/render-tui", "prodash/render-tui-crossterm", "prodash/progress-tree", "futures-lite"]
prodash-render-line = ["prodash/render-line", "prodash-render-line-crossterm", "prodash/progress-tree"]
cache-efficiency-debug = ["git-features/cache-efficiency-debug"]

[dependencies]
anyhow = "1.0.42"

gitoxide-core = { version ="^0.13.0", path = "gitoxide-core" }
git-features = { version ="^0.18.0", path = "git-features" }
git-repository = { version ="^0.13.0", path = "git-repository", default-features = false }

git-transport-for-configuration-only = { package = "git-transport", optional = true, version ="^0.14.0", path = "git-transport" }

clap = { version = "=3.0.0-rc.7", features = ["derive", "cargo"] }
prodash = { version = "16.0.0", optional = true, default-features = false }
atty = { version = "0.2.14", optional = true, default-features = false }
env_logger = { version = "0.9.0", optional = true, default-features = false, features = ["humantime", "termcolor", "atty"] }
crosstermion = { version = "0.8.0", optional = true, default-features = false }
futures-lite = { version = "1.12.0", optional = true, default-features = false, features = ["std"] }

[profile.dev.package]
git-object = { opt-level = 3 }
git-ref = { opt-level = 3 }
git-pack = { opt-level = 3 }
git-hash = { opt-level = 3 }
git-actor = { opt-level = 3 }
git-config = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
sha-1 = { opt-level = 3 }
sha1 = { opt-level = 3 }

[profile.release]
overflow-checks = false
lto = "fat"
# this bloats files but assures destructors are called, important for tempfiles. One day I hope we
# can wire up the 'abrt' signal handler so tempfiles will be removed in case of panics.
panic = 'unwind'
codegen-units = 1
incremental = false
build-override = { opt-level = 0 }

# It's not quite worth building depencies with more optimizations yet. Let's keep it here for later.
#[profile.dev.package."*"]
#opt-level = 2

[workspace]
members = [
    "git-actor",
    "git-url",
    "git-hash",
    "git-validate",
    "git-ref",
    "git-config",
    "git-features",
    "git-commitgraph",
    "git-object",
    "git-diff",
    "git-traverse",
    "git-index",
    "git-packetline",
    "git-transport",
    "git-protocol",
    "git-pack",
    "git-odb",
    "git-tempfile",
    "git-lock",
    "git-repository",
    "gitoxide-core",
    "git-tui",

    "experiments/object-access",
    "experiments/diffing",
    "experiments/traversal",

    "cargo-smart-release",

    "tests/tools",
]
exclude = ["cargo-smart-release/tests/fixtures/tri-depth-workspace/a",
           "cargo-smart-release/tests/fixtures/tri-depth-workspace/b",
           "cargo-smart-release/tests/fixtures/tri-depth-workspace/c"]
