[package]
name = "gix-revision"
version = "0.20.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with finding names for revisions and parsing specifications"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md", "README.md"]
rust-version = "1.65"

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = [ "dep:serde", "gix-hash/serde", "gix-object/serde" ]

[dependencies]
gix-hash = { version = "^0.12.0", path = "../gix-hash" }
gix-object = { version = "^0.35.0", path = "../gix-object" }
gix-date = { version = "^0.7.4", path = "../gix-date" }
gix-hashtable = { version = "^0.3.0", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.6.0", path = "../gix-revwalk" }
gix-trace = { version = "^0.1.3", path = "../gix-trace" }

bstr = { version = "1.3.0", default-features = false, features = ["std"]}
thiserror = "1.0.26"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-odb = { path = "../gix-odb" }
gix-testtools = { path = "../tests/tools" }
gix-commitgraph = { path = "../gix-commitgraph" }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
