[package]
name = "gix-status"
version = "0.1.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with 'git status'-like functionality"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>", "Pascal Kuthe <pascal.kuthe@semimod.de>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[dependencies]
gix-index = { version = "^0.24.0", path = "../gix-index" }
gix-fs = { version = "^0.6.0", path = "../gix-fs" }
gix-hash = { version = "^0.13.0", path = "../gix-hash" }
gix-object = { version = "^0.36.0", path = "../gix-object" }
gix-path = { version = "^0.10.0", path = "../gix-path" }
gix-features = { version = "^0.34.0", path = "../gix-features" }

thiserror = "1.0.26"
filetime = "0.2.15"
bstr = { version = "1.3.0", default-features = false }

