[package]
name = "git-refspec"
version = "0.1.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for parsing and representing refspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md", "README.md"]

[lib]
doctest = false

[dependencies]
git-revision = { version = "^0.4.4", path = "../git-revision" }
git-validate = { version = "^0.5.5", path = "../git-validate" }
git-hash = { version = "^0.9.9", path = "../git-hash" }

bstr = { version = "1.0.1", default-features = false, features = ["std"]}
thiserror = "1.0.26"
smallvec = "1.9.0"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
