[package]
name = "git-object"
version = "0.17.0"
description = "Immutable and mutable git objects with decoding and encoding support"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

[features]
serde1 = ["serde", "bstr/serde1", "smallvec/serde", "git-hash/serde1", "git-actor/serde1"]
verbose-object-parsing-errors = ["nom/std"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
git-features = { version = "^0.19.0", path = "../git-features", features = ["rustsha1"] }
git-hash = { version = "^0.9.0", path = "../git-hash" }
git-validate = { version ="^0.5.3", path = "../git-validate" }
git-actor = { version = "^0.8.0", path = "../git-actor" }

btoi = "0.4.2"
itoa = "1.0.1"
quick-error = "2.0.0"
hex = "0.4.2"
bstr = { version = "0.2.13", default-features = false, features = ["std", "unicode"] }
nom = { version = "7", default-features = false, features = ["std"]}
smallvec = { version = "1.4.0", features = ["write"] }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

[dev-dependencies]
pretty_assertions = "1.0.0"
git-testtools = { path = "../tests/tools"}
