lints.workspace = true

[package]
name = "gix-pathspec"
version = "0.13.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing magical pathspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.82"
include = ["src/**/*", "LICENSE-*", "README.md"]

[lib]
doctest = false

[dependencies]
gix-glob = { version = "^0.22.0", path = "../gix-glob" }
gix-path = { version = "^0.10.21", path = "../gix-path" }
gix-attributes = { version = "^0.28.0", path = "../gix-attributes" }
gix-config-value = { version = "^0.15.2", path = "../gix-config-value" }

bstr = { version = "1.12.0", default-features = false, features = ["std"] }
bitflags = "2"
thiserror = "2.0.17"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
serial_test = "3.1.1"
