[package]
name = "gix-hashtable"
version = "0.2.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate that provides hashtable based data structures optimized to utilize ObjectId keys"
authors = ["Pascal Kuthe <pascal.kuthe@semimod.de>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
parking_lot = "0.12.1"
hashbrown = { version = "0.13.1", default-features = false, features = [
  "inline-more",
  "raw"
] }
gix-hash = { version = "^0.11.2", path = "../gix-hash" }

