lints.workspace = true

[package]
name = "gix-utils"
version = "0.2.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate with `gitoxide` utilities that don't need feature toggles"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = true

[features]
bstr = ["dep:bstr"]

[dependencies]
fastrand = "2.0.0"
bstr = { version = "1.12.0", default-features = false, features = ["std"], optional = true }
unicode-normalization = { version = "0.1.19", default-features = false }
