[package]
name = "git-revision"
version = "0.10.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dealing with finding names for revisions and parsing specifications"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "CHANGELOG.md", "README.md"]
rust-version = "1.64"
autotests = false

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = [ "serde", "git-hash/serde1", "git-object/serde1" ]

[dependencies]
git-hash = { version = "^0.10.2", path = "../git-hash" }
git-object = { version = "^0.26.1", path = "../git-object" }
git-date = { version = "^0.4.2", path = "../git-date" }
git-hashtable = { version = "^0.1.1", path = "../git-hashtable" }

bstr = { version = "1.0.1", default-features = false, features = ["std"]}
thiserror = "1.0.26"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
document-features = { version = "0.2.1", optional = true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
