[package]
name = "git-revision"
version = "0.2.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dealing with finding names for revisions and parsing specifications"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = [ "serde", "git-hash/serde1", "git-object/serde1" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
git-hash = { version = "^0.9.4", path = "../git-hash" }
git-object = { version = "^0.19.0", path = "../git-object" }
git-date = { version = "^0.0.0", path = "../git-date" }

bstr = { version = "0.2.13", default-features = false, features = ["std"]}
hash_hasher = "2.0.3"
thiserror = "1.0.26"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-repository = { path = "../git-repository", default-features = false, features = ["unstable"] }
