lints.workspace = true

[package]
name = "gix-credentials"
version = "0.29.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project to interact with git credentials helpers"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-sec/serde"]

[dependencies]
gix-sec = { version = "^0.11.0", path = "../gix-sec" }
gix-url = { version = "^0.31.0", path = "../gix-url" }
gix-path = { version = "^0.10.17", path = "../gix-path" }
gix-command = { version = "^0.6.0", path = "../gix-command" }
gix-config-value = { version = "^0.15.0", path = "../gix-config-value" }
gix-prompt = { version = "^0.11.0", path = "../gix-prompt" }
gix-trace = { version = "^0.1.12", path = "../gix-trace" }

thiserror = "2.0.0"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
bstr = { version = "1.12.0", default-features = false, features = ["std"] }



document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-sec = { path = "../gix-sec" }
once_cell = "1.21.3"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
