[package]
name = "git-repository"
repository = "https://github.com/Byron/gitoxide"
description = "Abstractions for git repositories"
license = "MIT/Apache-2.0"
version = "0.14.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md"]

[lib]
doctest = false
test = true

[features]
default = ["max-performance", "one-stop-shop"]
unstable = ["git-index"]
serde1 = ["git-pack/serde1", "git-object/serde1", "git-protocol/serde1", "git-transport/serde1", "git-ref/serde1", "git-odb/serde1", "git-index/serde1"]
# enable when https://github.com/RustCrypto/asm-hashes/issues/17 is fixed
# max-performance = ["git-features/parallel", "git-features/zlib-ng-compat", "git-features/fast-sha1"]
max-performance = ["git-features/parallel", "git-features/zlib-ng-compat", "git-pack/pack-cache-lru-static", "git-pack/pack-cache-lru-dynamic"]
local-time-support = ["git-actor/local-time-support"]
async-network-client = ["git-protocol/async-client"]
blocking-network-client = ["git-protocol/blocking-client"]
blocking-http-transport = ["git-transport/http-client-curl"]
cache-efficiency-debug = ["git-features/cache-efficiency-debug"]
local = [
    "git-url",
    "git-diff",
]
one-stop-shop = [
    "local",
    "local-time-support"
]


[dependencies]
git-ref = { version = "^0.11.0", path = "../git-ref" }
git-tempfile = { version ="^1.0.0", path = "../git-tempfile" }
git-lock = { version ="^1.0.0", path = "../git-lock" }
git-validate = { version ="^0.5.3", path = "../git-validate" }

git-config = { version = "^0.1.11", path = "../git-config" }
git-odb = { version = "^0.26.0", path = "../git-odb" }
git-hash = { version = "^0.9.2", path = "../git-hash" }
git-object = { version = "^0.17.1", path = "../git-object" }
git-actor = { version = "^0.8.0", path = "../git-actor" }
git-pack = { version = "^0.16.1", path = "../git-pack", features = ["object-cache-dynamic"] }

git-url = { version = "^0.3.5", path = "../git-url", optional = true }
git-traverse = { version = "^0.12.0", path = "../git-traverse" }
git-protocol = { version = "^0.14.0", path = "../git-protocol", optional = true }
git-transport = { version = "^0.15.0", path = "../git-transport", optional = true }
git-diff = { version = "^0.13.0", path = "../git-diff", optional = true }
git-features = { version = "^0.19.1", path = "../git-features", features = ["progress"] }

# unstable only
git-index = { version ="^0.1.0", path = "../git-index", optional = true }

signal-hook = { version = "0.3.9", default-features = false }
thiserror = "1.0.26"
clru = "0.5.0"
byte-unit = "4.0.13"
log = "0.4.14"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
signal-hook = { version = "0.3.9", default-features = false }
anyhow = "1"
tempfile = "3.2.0"
