name: Report undesirable behaviour  🐛
description: Create an issue to help us improve
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! ❤️
  - type: textarea
    attributes:
      label: Current behavior 😯
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior 🤔
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Git behavior
      description: Describe what Git does under similar circumstances.
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: Describe how we can reproduce the behaviour.
      placeholder: |
        1.
        2.
        3. …
