name: Report undesirable behaviour  🐛
description: Create an issue to help us improve
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates
      description: |
        Please [search the history](https://github.com/o2sh/onefetch/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current behavior 😯
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior 🤔
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: Describe how we can reproduce the behaviour.
      placeholder: |
        1.
        2.
        3. …
