lints.workspace = true

[package]
name = "gix-archive"
version = "0.20.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "archive generation from of a worktree stream"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
default = ["tar", "tar_gz", "zip"]

## Enable the `tar` archive format. It has support for all information, except for object ids.
tar = ["dep:tar", "dep:gix-path"]
## Enable the `tar.gz` archive format.
tar_gz = ["tar", "dep:flate2"]

## Enable the `zip` archive format.
## This also enables the `flate2` dependency in order to enable `zlib-rs` on it.
zip = ["dep:flate2", "dep:zip"]


[dependencies]
gix-worktree-stream = { version = "^0.20.0", path = "../gix-worktree-stream" }
gix-object = { version = "^0.48.0", path = "../gix-object" }
gix-path = { version = "^0.10.15", path = "../gix-path", optional = true }
gix-date = { version = "^0.9.4", path = "../gix-date" }

flate2 = { version = "1.1.1", optional = true, default-features = false, features = ["zlib-rs"] }
zip = { version = "2.6.1", optional = true, default-features = false, features = ["deflate"] }
jiff = { version = "0.2.6", default-features = false, features = ["std"] }

thiserror = "2.0.0"
bstr = { version = "1.12.0", default-features = false }

tar = { version = "0.4.38", optional = true }

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-odb = { path = "../gix-odb" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = [
    "attributes",
] }
gix-hash = { path = "../gix-hash" }
gix-attributes = { path = "../gix-attributes" }
gix-object = { path = "../gix-object" }
gix-filter = { path = "../gix-filter" }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
