[package]
name = "gix-traverse"
version = "0.24.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*"]
rust-version = "1.64"
autotests = false

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.10.2", path = "../gix-hash" }
gix-object = { version = "^0.28.0", path = "../gix-object" }
gix-hashtable = { version = "^0.1.2", path = "../gix-hashtable" }
thiserror = "1.0.32"
