[package]
name = "gix-traverse"
version = "0.36.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.70"
autotests = false

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.14.0", path = "../gix-hash" }
gix-object = { version = "^0.40.0", path = "../gix-object" }
gix-date = { version = "^0.8.2", path = "../gix-date" }
gix-hashtable = { version = "^0.5.0", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.11.0", path = "../gix-revwalk" }
gix-commitgraph = { version = "^0.23.0", path = "../gix-commitgraph" }
smallvec = "1.10.0"
thiserror = "1.0.32"
