lints.workspace = true

[package]
name = "gix-filter"
version = "0.18.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing git filters"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.17.0", path = "../gix-hash" }
gix-trace = { version = "^0.1.12", path = "../gix-trace" }
gix-object = { version = "^0.48.0", path = "../gix-object" }
gix-command = { version = "^0.5.0", path = "../gix-command" }
gix-quote = { version = "^0.5.0", path = "../gix-quote" }
gix-utils = { version = "^0.2.0", path = "../gix-utils" }
gix-path = { version = "^0.10.15", path = "../gix-path" }
gix-packetline-blocking = { version = "^0.18.3", path = "../gix-packetline-blocking" }
gix-attributes = { version = "^0.25.0", path = "../gix-attributes" }

encoding_rs = "0.8.32"
bstr = { version = "1.12.0", default-features = false, features = ["std"] }
thiserror = "2.0.0"
smallvec = "1.15.0"


[dev-dependencies]
serial_test = { version = "3.1.0", default-features = false }
gix-testtools = { path = "../tests/tools" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"] }
