lints.workspace = true

[package]
name = "gix-filter"
version = "0.20.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing git filters"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.70"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.19.0", path = "../gix-hash" }
gix-trace = { version = "^0.1.13", path = "../gix-trace" }
gix-object = { version = "^0.50.2", path = "../gix-object" }
gix-command = { version = "^0.6.2", path = "../gix-command" }
gix-quote = { version = "^0.6.0", path = "../gix-quote" }
gix-utils = { version = "^0.3.0", path = "../gix-utils" }
gix-path = { version = "^0.10.20", path = "../gix-path" }
gix-packetline-blocking = { version = "^0.19.1", path = "../gix-packetline-blocking" }
gix-attributes = { version = "^0.27.0", path = "../gix-attributes" }

encoding_rs = "0.8.32"
bstr = { version = "1.12.0", default-features = false, features = ["std"] }
thiserror = "2.0.17"
smallvec = "1.15.1"


[dev-dependencies]
serial_test = { version = "3.1.0", default-features = false }
gix-testtools = { path = "../tests/tools" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"] }
