lints.workspace = true

[package]
name = "gix-date"
version = "0.10.1"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project parsing dates the way git does"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.70"

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde"]

[dependencies]
bstr = { version = "1.12.0", default-features = false, features = ["std"] }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
itoa = "1.0.1"
jiff = "0.2.10"
thiserror = "2.0.0"
# TODO: used for quick and easy `TimeBacking: std::io::Write` implementation, but could make that `Copy`
#       and remove this dep with custom impl
smallvec = { version = "1.15.0", features = ["write"] }

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
gix-hash = { path = "../gix-hash" }
gix-testtools = { path = "../tests/tools" }
once_cell = "1.21.3"
pretty_assertions = "1.4.1"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
