[package]
name = "git-ref"
version = "0.12.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate to handle git references"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = ["serde", "git-hash/serde1", "git-actor/serde1", "git-object/serde1"]
internal-testing-git-features-parallel = ["git-features/parallel"] # test sorted parallel loose file traversal

[[test]]
name = "refs-parallel-fs-traversal"
path = "tests/refs-parallel.rs"
required-features = ["internal-testing-git-features-parallel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-features = { version = "^0.20.0", path = "../git-features", features = ["walkdir"]}
git-path = { version = "^0.1.0", path = "../git-path" }
git-hash = { version = "^0.9.3", path = "../git-hash" }
git-object = { version = "^0.18.0", path = "../git-object" }
git-validate = { version ="^0.5.3", path = "../git-validate" }
git-actor = { version = "^0.9.0", path = "../git-actor" }
git-lock = { version = "^2.0.0", path = "../git-lock" }
git-tempfile = { version = "^2.0.0", path = "../git-tempfile" }

quick-error = "2.0.0"
nom = { version = "7", default-features = false, features = ["std"]}
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

# packed refs
memmap2 = "0.5.0"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-odb = { path = "../git-odb" }
tempfile = "3.2.0"
