[package]
name = "git-ref"
version = "0.24.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate to handle git references"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*"]
rust-version = "1.64"
autotests = false

[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = ["serde", "git-hash/serde1", "git-actor/serde1", "git-object/serde1"]

[dependencies]
git-features = { version = "^0.26.4", path = "../git-features", features = ["walkdir"]}
git-path = { version = "^0.7.1", path = "../git-path" }
git-hash = { version = "^0.10.2", path = "../git-hash" }
git-object = { version = "^0.26.1", path = "../git-object" }
git-validate = { version = "^0.7.2", path = "../git-validate" }
git-actor = { version = "^0.17.1", path = "../git-actor" }
git-lock = { version = "^3.0.0", path = "../git-lock" }
git-tempfile = { version = "^3.0.0", path = "../git-tempfile" }

thiserror = "1.0.34"
nom = { version = "7", default-features = false, features = ["std"]}
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

# packed refs
memmap2 = "0.5.0"

document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
tempfile = "3.2.0"


[package.metadata.docs.rs]
features = ["document-features", "serde1"]
rustdoc-args = ["--cfg", "docsrs"]
