[package]
name = "gix-dir"
version = "0.3.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with directory walks"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-trace = { version = "^0.1.8", path = "../gix-trace" }
gix-index = { version = "^0.31.1", path = "../gix-index" }
gix-discover = { version = "^0.31.0", path = "../gix-discover" }
gix-fs = { version = "^0.10.1", path = "../gix-fs" }
gix-path = { version = "^0.10.7", path = "../gix-path" }
gix-pathspec = { version = "^0.7.2", path = "../gix-pathspec" }
gix-worktree = { version = "^0.32.0", path = "../gix-worktree", default-features = false }
gix-object = { version = "^0.42.1", path = "../gix-object" }
gix-ignore = { version = "^0.11.2", path = "../gix-ignore" }
gix-utils = { version = "^0.1.11", path = "../gix-utils", features = ["bstr"] }

bstr = { version = "1.5.0", default-features = false }
thiserror = "1.0.34"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-fs = { path = "../gix-fs" }
pretty_assertions = "1.4.0"
