[package]
name = "gix-ref"
version = "0.29.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate to handle git references"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*"]
rust-version = "1.64"
autotests = false

[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-actor/serde", "gix-object/serde"]

[dependencies]
gix-features = { version = "^0.29.0", path = "../gix-features", features = ["walkdir"]}
gix-fs = { version = "^0.1.1", path = "../gix-fs" }
gix-path = { version = "^0.8.0", path = "../gix-path" }
gix-hash = { version = "^0.11.1", path = "../gix-hash" }
gix-object = { version = "^0.29.2", path = "../gix-object" }
gix-validate = { version = "^0.7.3", path = "../gix-validate" }
gix-actor = { version = "^0.20.0", path = "../gix-actor" }
gix-lock = { version = "^5.0.0", path = "../gix-lock" }
gix-tempfile = { version = "^5.0.0", default-features = false, path = "../gix-tempfile" }

thiserror = "1.0.34"
nom = { version = "7", default-features = false, features = ["std"]}
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

# packed refs
memmap2 = "0.5.0"

document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-utils = { path = "../gix-utils" }
tempfile = "3.2.0"


[package.metadata.docs.rs]
features = ["document-features", "serde"]
rustdoc-args = ["--cfg", "docsrs"]
