[package]
name = "gix-config-value-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
gix-config-value = { path = ".." }
anyhow = "1.0.78"
bstr = "1.9.0"
arbitrary = { version = "1.3.2", features = ["derive"] }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_value"
path = "fuzz_targets/fuzz_value.rs"
test = false
doc = false
