[package]
name = "gix-fs"
version = "0.1.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate providing file system specific utilities to `gitoxide`"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.64"

[lib]
doctest = false

[dependencies]
gix-features = { version = "0.29.0", path = "../gix-features" }

[dev-dependencies]
tempfile = "3.5.0"
