name: cron

on:
  schedule:
    - cron: '0 13,1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: stress
        run: make stress
