name: Minimum Supported Rust Version

on:
  push:
    branches:
      - main
      - 'run-ci/**'
      - '**/run-ci/**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-msrv:
    name: cargo check MSRV

    strategy:
      matrix:
        os:
          - windows-2022
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    env:
      # This is dictated by `firefox` to support the `helix` editor, but now probably effectively
      # be controlled by `jiff`, which also aligns with `regex`.
      # IMPORTANT: When adjusting, change all occurrences in `etc/msrv-badge.svg` as well.
      RUST_VERSION: 1.75.0

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Set up ${{ env.RUST_VERSION }} (MSRV) and nightly toolchains
        run: rustup toolchain install ${{ env.RUST_VERSION }} nightly --profile minimal --no-self-update
      - name: Set ${{ env.RUST_VERSION }} (MSRV) as default
        run: rustup default ${{ env.RUST_VERSION }}
      - name: Downgrade locked dependencies to lowest allowed versions
        run: |
          # TODO(msrv): Use `cargo update --minimal-versions` when `--minimal-versions` is available.
          cargo +nightly update -Zminimal-versions
      - name: Run some `cargo build` commands on `gix`
        run: just ci-check-msrv
