name: Minimum Supported Rust Version

on:
  # Trigger the workflow on push to master or any pull request
  # Ignore all tags
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  rustfmt:
    name: cargo check MSRV
    strategy:
      matrix:
        os:
          - windows-2019
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      # dictated by `firefox` to support the `helix` editor, but now driven by the `time` crate. IMPORTANT: adjust etc/msrv-badge.svg as well
      rust_version: 1.67.0
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: |
          rustup toolchain install ${{ env.rust_version }} --profile minimal --no-self-update
          rustup default ${{ env.rust_version }}
      - run: just ci-check-msrv
